RIP_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("base/", views.base, name="base"),
    path("admin/", admin.site.urls),
    path("", views.main, name="main"),
    path("home/", views.home, name="home"),
    path("accounts/", include("accounts.urls")),
    path("articles/", include("articles.urls")),
    path("champions/", include("champions.urls")),
    path("summoners/", include("summoners.urls")),
    # summernote
    path("summernot/", include("django_summernote.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

# 비밀번호 초기화, 재설정
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse_lazy

app_name = "accounts"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("signup/", views.signup, name="signup"),  # 회원가입
    path("logout/", views.logout, name="logout"),  # 로그아웃
    path("<int:pk>/", views.detail, name="detail"),
    path('<int:pk>/report/', views.report, name='report'),
    path("<int:user_pk>/mypage/", views.mypage, name="mypage"),  # 마이페이지
    path("<int:user_pk>/password/", views.password, name="password"),  # 비밀번호 변경
    path("delete/", views.delete, name="delete"),  # 회원탈퇴
    path("<int:user_pk>/pre_delete/", views.pre_delete, name="pre_delete"),  # 회원탈퇴
    path("<int:pk>/update/", views.update, name="update"),  # 회원정보수정
    path(
        "password/reset/",
        views.UserPasswordResetView.as_view(
            template_name="accounts/password_reset.html",
            email_template_name="accounts/password_reset_email.html",
            success_url=reverse_lazy("accounts:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password/reset/done/",
        views.UserPasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password/reset/confirm/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy("accounts:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password/reset/confirm/complete/",
        views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("send_email/", views.send_email, name="send_email"),
    path("member/", views.member, name="member"),  # 프로그래스바
    path("login/kakao", views.kakao_request, name="kakao"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao_callback"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    kakao_id = models.BigIntegerField(null=True, unique=True)
    birthday = models.DateTimeField(default=timezone.now)
    email = models.EmailField(max_length=100)
    agree = models.BooleanField(null=False, default=False)
    # agree_privacy = models.BooleanField(null=False, default=False)
    # agree_mail = models.BooleanField(null=False, default=False)


# 마이페이지 프로필
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    intro = models.TextField(blank=True)  # 소개글

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model
from .models import *
from django.forms import ModelForm


class DateInput(forms.DateInput):
    input_type = "Date"


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
            "birthday",
            "agree",
        )
        widgets = {"birthday": DateInput()}
        labels = {
            "username": "닉네임",
        }


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User()
        fields = ["username"]
        labels = {
            "username": "닉네임",
        }


class ProfileForm(ModelForm):
    class Meta:
        model = Profile()
        fields = ["intro"]

accounts/views.py
import random
import requests
from django.shortcuts import render, redirect, get_object_or_404
# from articles.models import Grade
from .forms import CustomUserCreationForm, ProfileForm
from .models import *
from .forms import *
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.core.mail.message import EmailMessage
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
)
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm,
)
from django.shortcuts import resolve_url

UserModel = get_user_model()
INTERNAL_RESET_URL_TOKEN = "set-password"
INTERNAL_RESET_SESSION_TOKEN = "_password_reset_token"


# Create your views here.
def login(request):
    # if request.user.is_anonymous:
    if request.method == "POST":
        login_form = AuthenticationForm(request, data=request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect("home")

    else:
        login_form = AuthenticationForm()

    context = {
        "login_form": login_form,
    }
    print(context)
    return render(request, "accounts/login.html", context)


# else:
#    return HttpResponseRedirect("")


def logout(request):
    auth_logout(request)
    return redirect("main")


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)  # 프로필 생성
            auth_login(
                request, user, backend="django.contrib.auth.backends.ModelBackend"
            )
            return redirect("main")

    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    articles = user.article_set.all()
    like_articles = user.like_post.all()
    bookmark_articles = user.bookmark_post.all()
    grade = ''

    article_set = user.article_set.all()
    comment_set = user.comment_set.all()
    a_count = article_set.count()
    c_count = comment_set.count()

    if c_count > 20 and a_count > 10:
        grade = '썩은물'
    elif c_count > 10 and a_count > 4:
        grade = '고인물'
    elif c_count > 2 and a_count > 2:
        grade = '탁한물'
    elif c_count > 2 or a_count > 0:
        grade = '맑은물'
    elif c_count <= 2 or a_count == 0:
        grade = '신선한물'
    context = {
        "grade":grade,
        "user": user,
        "articles": articles,
        "like_articles": like_articles,
        "bookmark_articles": bookmark_articles,
    }
    return render(request, "accounts/detail.html", context)


# 마이 페이지 (회원 정보로 이동, 비밀번호 변경, 로그아웃, 회원탈퇴)
@login_required
def mypage(request, user_pk):
    user = get_user_model().objects.get(pk=user_pk)
    articles = user.article_set.all()
    like_articles = user.like_post.all()
    bookmark_articles = user.bookmark_post.all()

    # 업데이트
    if request.user.profile:
        profile = request.user.profile

        if request.method == "POST":
            profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
            change_form = CustomUserChangeForm(request.POST, instance=user)

            if profile_form.is_valid() and change_form.is_valid():
                profile_form.save()
                change_form.save()
                # return redirect('accounts:detail', request.user.pk)
                return redirect("accounts:mypage", request.user.pk)
        else:
            profile_form = ProfileForm(instance=profile)
            change_form = CustomUserChangeForm(instance=user)

    # 최초 생성
    else:
        if request.method == "POST":
            profile_form = ProfileForm(request.POST, request.FILES)
            change_form = CustomUserChangeForm(request.POST, instance=user)

            if profile_form.is_valid() and change_form.is_valid():
                profile_form.save()
                change_form.save()
                # return redirect('accounts:detail', request.user.pk)
                return redirect("accounts:mypage", request.user.pk)

        else:
            profile_form = ProfileForm
            change_form = CustomUserChangeForm(instance=user)

    context = {
        "profile_form": profile_form,
        "change_form": change_form,
        "user": user,
        "articles": articles,
        "like_articles": like_articles,
        "bookmark_articles": bookmark_articles,
    }

    return render(request, "accounts/mypage.html", context)


# 비밀번호 변경
@login_required
def password(request, user_pk):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)  # 로그인 유지
            return redirect("accounts:mypage", user_pk)

    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }

    return render(request, "accounts/password.html", context)


# 회원 탈퇴


def pre_delete(request, user_pk):
    return render(request, "accounts/pre_delete.html")


def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)

    return redirect("articles:index")


# 회원 프로필 (프로필 사진, 소개글) (+ 닉네임?)
@login_required
def update(request, pk):
    user = get_user_model().objects.get(pk=pk)
    articles = user.article_set.all()
    like_articles = user.like_post.all()
    bookmark_articles = user.bookmark_post.all()

    # 업데이트
    if request.user.profile:
        profile = request.user.profile

        if request.method == "POST":
            profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
            change_form = CustomUserChangeForm(request.POST, instance=user)

            if profile_form.is_valid() and change_form.is_valid():
                profile_form.save()
                change_form.save()
                # return redirect('accounts:detail', request.user.pk)
                return redirect("accounts:update", request.user.pk)
        else:
            profile_form = ProfileForm(instance=profile)
            change_form = CustomUserChangeForm(instance=user)

    # 최초 생성
    else:
        if request.method == "POST":
            profile_form = ProfileForm(request.POST, request.FILES)
            change_form = CustomUserChangeForm(request.POST, instance=user)

            if profile_form.is_valid() and change_form.is_valid():
                profile_form.save()
                change_form.save()
                # return redirect('accounts:detail', request.user.pk)
                return redirect("accounts:update", request.user.pk)

        else:
            profile_form = ProfileForm
            change_form = CustomUserChangeForm(instance=user)

    context = {
        "profile_form": profile_form,
        "change_form": change_form,
        "user": user,
        "articles": articles,
        "like_articles": like_articles,
        "bookmark_articles": bookmark_articles,
    }

    return render(request, "accounts/update.html", context)

    # 최초 생성
    # else:
    # if request.method == "POST":
    #     profile_form = ProfileForm(request.POST, request.FILES)
    #     change_form = CustomUserChangeForm(request.POST, instance=user)

    #     if profile_form.is_valid() and change_form.is_valid():
    #         profile_form.save()
    #         change_form.save()
    #         # return redirect('accounts:detail', request.user.pk)
    #         return redirect("accounts:mypage", request.user.pk)

    # else:
    #     profile_form = ProfileForm()
    #     change_form = CustomUserChangeForm(instance=user)


@login_required
def report(request, pk):
    # 프로필에 해당하는 유저를 로그인한 유저가!
    user = get_object_or_404(get_user_model(), pk=pk)
    if request.user == user:
        messages.warning(request, "스스로 신고 할 수 없습니다.")
        return redirect("accounts:detail", pk)
    if request.user in user.reported.all():
        messages.warning(request, "이미 신고한 게시글입니다.")
    else:
        user.reported.add(request.user)
    return redirect("accounts:detail", pk)


def send_email(request):
    subject = "RIP.gg 비밀번호 재설정"
    message = render_to_string("password_reset_email.html")
    send_email = EmailMessage(subject, message)
    send_email.send()


def member(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)  # 프로필 생성
            auth_login(
                request, user, backend="django.contrib.auth.backends.ModelBackend"
            )
            return redirect("main")

    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/member.html", context)


@login_required
def articles(request, pk):
    articles = all.Articles.objects.filter(user=request.user).order_by("-pk")
    context = {
        "articles": articles,
    }
    return render(request, "accounts/articles.html", context)


import secrets

state_token = secrets.token_urlsafe(16)


def kakao_request(request):
    kakao_api = "https://kauth.kakao.com/oauth/authorize?"

accounts/templates/accounts/login.html
{% extends 'nonavbase.html' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}

{% block title %} LOGIN{% endblock title %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}" type="text/css">
{% endblock%}
{% block content %}
<div class="login_section">
  <!-- <section class="col-6 border border-3 rounded-3"> -->
  <div class="login_box">   
    <div class="login_img">
    <a href="{% url 'main' %}">
      <img src="{% static 'images/검정로고.png' %}" width="150" alt="">
    </a>
    </div>
    <div class="mt-3 d-flex justify-content-start">
      간편 로그인
    </div>
    <div class="mt-1">
      <form action="{% url 'accounts:login' %}kakao" method='GET'>
        <button class="btnkakao">
          <i style="color: rgb(28, 16, 0)" class="fa-solid fa-comment"></i><span style="font-weight: bold; color: rgb(28, 16, 0); padding: 5px">카카오로 로그인하기</span>
        </button>
        <!-- <input type="submit" class="btn btn-warning col-6 my-2" value="카카오로 로그인하기"/> -->
      </form>
    </div>
    <div class="login_or">OR</div>
    <form action="" method='POST'>
      {% csrf_token %}
        <!-- 이메일 -->
      <div class="form_wrap_line login_top">
        <p>
          <input type="text" id="user_id" autocomplete="off" name="username" required>
          <label for="user_name"><span>이메일 주소</span></label>
        </p>
        <!-- 비밀번호 -->
        <p>
          <input type="password" id="user_pw" autocomplete="off" name="password" required>
          <label for="user_password"><span>비밀번호</span></label>
        </p>
        <input  class="login_btn" id="btn_login"type="submit" value="LOGIN" />
      </div>
      <div class="login_box2">
        <div class="text-center p-1">RIP.GG에 처음이신가요?
          <a class="to-signup" href="{% url 'accounts:member' %}">
            <b>회원 가입<i class="bi bi-person-fill-add"></i>
            </b>
          </a>
        </div>
        <div class="text-center p-1">비밀번호를 잃어버리셨나요?
          <a href="{% url 'accounts:password_reset' %}">
            <b>비밀번호 찾기<i class="bi bi-person-fill-add"></i>
            </b>
          </a>
        </div>
      </div>
    </form>
  </div>
  <!-- </section> -->
</div>
{% endblock content %}

accounts/templates/accounts/member.html
{% extends 'nonavbase.html' %}
{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% block title %}member{% endblock %}
{% block css %}
<style>
body {
    background-color: #f3f5f7;
}

</style>


{% endblock %}
{% block content %}
<div class="container">
    <div class="sign_box">
        <div class="sign_box_bg">
            <div class="logo"><a href="{% url 'main' %}">
                <img src="/static/images/검정로고.png" alt="" style="width: 200px; padding-bottom: 15px;"></a>
            </div>
            <form action="" method="POST" id="form__wrap" data-multi-step style="background-color: #fff;">
                {% csrf_token %}
                <!-- 생년월일 -->
                <div class="card" data-step>
                    <div class="iBox">
                        <i class="fa-solid fa-circle" style="color: #1ea1f7;"></i>
                        <i class="fa-solid fa-circle" style="color: #e9edef"></i>
                        <i class="fa-solid fa-circle" style="color: #e9edef"></i>
                    </div>
                    <div class="pw_title">
                        생년월일 입력
                    </div>
                    <div class="">
                        <p class="">
                            <input id="" type="Date" name="birthday" value="" placeholder="생년월일" required="" id="id_birthday" required>
                            <input type="hidden" name="initial-birthday" value=""id="initial-id_birthday">
                        </p>
                    </div>
                    <div class="progBtn1">
                        <button id="" class="memberBtn" type="button" data-next >다음</button>
                    </div>
                    <div class="d-flex justify-content-center login_box2">
                        아이디가 있으신가요?<a href="{% url 'accounts:login' %}">로그인 하기</a>
                    </div>
                </div>
                <div class="card" data-step>
                    <div class="iBox">
                        <i class="fa-solid fa-circle" style="color: #e9edef"></i>
                        <i class="fa-solid fa-circle" style="color: #1ea1f7;"></i>
                        <i class="fa-solid fa-circle" style="color: #e9edef"></i>
                    </div>
                    <!-- 약관 동의 -->
                    <div class="checkall">
                        <span class="member-agree-checkbox_state">
                            <input type="checkbox" name="checkAll" id="checkAll" />
                        </span>
                        <label for="checkAll" class="member-agree-checkbox_label"
                        >이용약관, 개인정보 수집 및 이용, 프로모션 알림 메일 및 푸시 알림 수신(선택)에 모두 동의합니다.</label>
                    </div>
                    <div class="">
                        <div class="">
                            <div class="check1 input__check">
                                <span class="member-agree-checkbox_state">
                                    <input type="checkbox" name="agree_service" id="termsOfService" value="termsOfService" required />
                                </span>
                                <label for="privacyPolicy" class="member-agree-checkbox_label required">RIP.GG 이용약관 동의</label>
                            </div>
                            <div class="croll-touch check terms__content">
                                여러분을 환영합니다. RIP.GG 서비스 및 제품(이하 ‘서비스’)을 이용해 주셔서 감사합니다. 본 약관은 다양한 RIP.GG
                                서비스의 이용과 관련하여 RIP.GG 서비스를 제공하는 RIP.GG 주식회사(이하 ‘RIP.GG’)와 이를 이용하는 RIP.GG 서비스
                                회원(이하 ‘회원’) 또는 비회원과의 관계를 설명하며, 아울러 여러분의 RIP.GG 서비스 이용에 도움이 될 수 있는
                                유익한 정보를 포함하고 있습니다. RIP.GG 서비스를 이용하시거나 RIP.GG 서비스 회원으로 가입하실 경우 여러분은 본
                                약관 및 관련 운영 정책을 확인하거나 동의하게 되므로, 잠시 시간을 내시어 주의 깊게 살펴봐 주시기
                                바랍니다.
                            </div>
                        </div>
                        <div class="">
                            <div class="check1 input__check">
                                <span class="member-agree-checkbox_state">
                                    <input type="checkbox" name="agree_privacy" id="privacyPolicy" value="privacyPolicy" required />
                                </span>
                                <label for="privacyPolicy" class="member-agree-checkbox_label required">개인정보 수집 및 이용 동의</label>
                            </div>
                            <div class="croll-touch check terms__content">
                                개인정보보호법에 따라 RIP.GG에 회원가입 신청하시는 분께 수집하는 개인정보의 항목, 개인정보의 수집 및
                                이용목적, 개인정보의 보유 및 이용기간, 동의 거부권 및 동의 거부 시 불이익에 관한 사항을 안내 드리오니
                                자세히 읽은 후 동의하여 주시기 바랍니다.1. 수집하는 개인정보 이용자는 회원가입을 하지 않아도 정보 검색,
                                뉴스 보기 등 대부분의 네이버 서비스를 회원과 동일하게 이용할 수 있습니다. 이용자가 메일, 캘린더, 카페,
                                블로그 등과 같이 개인화 혹은 회원제 서비스를 이용하기 위해 회원가입을 할 경우, 네이버는 서비스 이용을
                                위해 필요한 최소한의 개인정보를 수집합니다.
                            </div>
                        </div>
                        <div class="">
                            <div class="check1 input__check">
                                <span class="member-agree-checkbox_state">
                                    <input type="checkbox" name="agree_mail" id="allowPromotions" value="allowPromotions" />
                                </span>
                                <label for="allowPromotions" class="member-agree-checkbox_label"> 이벤트 등 프로모션 알림 및 푸시 알림 수신<span class="check2">(선택)</span></label>
                            </div>
                            <div class="croll-touch check terms__content">
                                RIP.GG에서 제공하는 이벤트/혜택 등 다양한 정보를 휴대전화(RIP.GG앱 알림 또는 문자), 이메일로 받아보실 수
                                있습니다. 일부 서비스(별도 회원 체계로 운영하거나 RIP.GG 가입 이후 추가 가입하여 이용하는 서비스 등)의
                                경우, 개별 서비스에 대해 별도 수신 동의를 받을 수 있으며, 이때에도 수신 동의에 대해 별도로 안내하고
                                동의를 받습니다.
                            </div>
                        </div>
                    </div> 
                    <div class="progBtn2">
                        <!-- <button class="memberBtn previousBtn" type="button" data-previous>Previous</button>         -->
                        <a href="{% url 'home' %}" class="memberBtn previousBtn" type="button">비동의</a>        
                        <button class="memberBtn" type="button" data-next>다음</button>
                    </div>
                </div>
                <div class="card" data-step>
                    <!-- 기본 정보 -->
                    <div class="iBox">
                        <i class="fa-solid fa-circle" style="color: #e9edef"></i>
                        <i class="fa-solid fa-circle" style="color: #e9edef"></i>
                        <i class="fa-solid fa-circle" style="color: #1ea1f7;"></i>
                    </div>
                    <div class="pw_title">
                        기본정보 입력
                    </div>
                    <p class="">
                        <input id="user_id" type="text" name="email" maxlength="100" required=" autocomplete="off" required>
                        <label for="user_id"><span>이메일</span></label>
                    </p>
                    <p class="">
                        <input id="user_nick" type="text" name="username" maxlength="150" autofocus="" required="">
                        <label for="user_nick"><span>닉네임</span></label>
                    </p>
                    <div class="form-text">
                        개인정보를 기입하여 발생될 수 있는 피해는 RIP.GG가 일절 책임지지 않습니다.
                    </div>
                    <p class="">
                        <input id="user_pw" type="password" name="password1" autocomplete="new-password" required="">
                        <label for="user_pw"><span>비밀번호</span></label>
                    </p>
                    <p class="">
                        <input id="pwFormT" type="password" name="password2" autocomplete="new-password" required="">
                        <label for="pwFormT"><span>비밀번호확인</span></label>
                    </p>
                    <div class="progBtn2">
                        <a class="memberBtn previousBtn" href="{% url 'home' %}">취소</a>
                        <button class="memberBtn" type="submit">완료</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% block script %}

<script src="/static/js/accounts.js" defer></script>


{% endblock %}
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'nonavbase.html' %}
{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% block title %}member{% endblock %}
{% block css %}
<style>
body {
    background-color: #f3f5f7;
}
.input-control.success input {
    border-color: #09c372;
}

.input-control.error input {
    border-color: #ff3860;
}

.input-control .error {
    color: #ff3860;
    font-size: 9px;
    height: 13px;
}

</style>


{% endblock %}
{% block content %}
<div class="login_section">
  <!-- <section class="col-6 border border-3 rounded-3"> -->
  <div class="login_box">
    <div class="memberbox_inner">
      <div class="login_img">
        <img src="{% static 'images/검정로고.png' %}" width="150" alt="">
      </div>
      <h5 class="pw_title">비밀번호 찾기</h5>
      <div class="pw_title_sub">비밀번호를 찾고자 하는 RIP.GG 이메일 ID를 입력해주시면 해당 메일 주소로 비밀번호 재설정 링크를 보내드립니다.</div>    
      <form action="" id="form" method='POST'>
      {% csrf_token %}
          <!-- 비밀번호 요청 이메일 -->
        <p>
            <input id="email" type="text" name="email" autocomplete="off" maxlength="254" required="" id="id_email" required>
            <label for="id_email"><span>이메일</span></label>
        </p>
        <div style="pw_btn_box ">
          <input class="memberBtn nomarginBtn" type="submit" value="이메일 보내기">
        </div>
      </form>
      <div class="pw_btn_box back_login">
        <a href="{% url 'accounts:login' %}">로그인으로 돌아가기</a>
      </div>
    </div>   
  </div>
</div>
{% block script %}
<script>  


</script>

{% endblock %}
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'nonavbase.html' %}
{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% block title %} member{% endblock %}
{% block css %}
<style>
body {
    background-color: #f3f5f7;
}
.input-control.success input {
    border-color: #09c372;
}

.input-control.error input {
    border-color: #ff3860;
}

.input-control .error {
    color: #ff3860;
    font-size: 9px;
    height: 13px;
}

</style>


{% endblock %}
{% block content %}
<div class="login_section">
  <!-- <section class="col-6 border border-3 rounded-3"> -->
  <div class="login_box">
    <div class="memberbox_inner">
      <div class="login_img">
        <img src="{% static 'images/검정로고.png' %}" width="150" alt="">
      </div>
      <h5 class="pw_title">비밀번호 변경 완료</h5>
      <div class="pw_title_sub">다시 로그인 해주세요.</div>
        <div class="pw_btn_box back_login">
        <a type="button" class="memberBtn nomarginBtn" href="{% url 'accounts:login' %}">로그인 하기</a>
        </div>
        <div class="text-center">
            <a cless="text-center"  href="{% url 'home' %}">홈으로</a>
        </div>
    </div>   
  </div>
</div>
{% block script %}
<script>  


</script>

{% endblock %}
{% endblock %}

accounts/templates/accounts/password_reset_email.html
{% autoescape off %}
안녕하세요 {{ user.email }}님 RIP.GG 비밀번호 변경에 관한 메일입니다. 아래의 링크로 접속하여 비밀번호를 변경해주세요.
아래 링크를 클릭하세요:
http://ripggbean-env.eba-tprx3bfx.ap-northeast-2.elasticbeanstalk.com{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
위의 링크를 클릭할 수 없는 경우 URL을 복사하여 새 브라우저에 붙여넣어주세요.
{% endautoescape %}