RIP_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("base/", views.base, name="base"),
    path("admin/", admin.site.urls),
    path("", views.main, name="main"),
    path("home/", views.home, name="home"),
    path("accounts/", include("accounts.urls")),
    path("articles/", include("articles.urls")),
    path("champions/", include("champions.urls")),
    path("summoners/", include("summoners.urls")),
    # summernote
    path("summernot/", include("django_summernote.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

# 비밀번호 초기화, 재설정
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse_lazy

app_name = "accounts"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("signup/", views.signup, name="signup"),  # 회원가입
    path("logout/", views.logout, name="logout"),  # 로그아웃
    path("<int:pk>/", views.detail, name="detail"),
    path('<int:pk>/report/', views.report, name='report'),
    path("<int:user_pk>/mypage/", views.mypage, name="mypage"),  # 마이페이지
    path("<int:user_pk>/password/", views.password, name="password"),  # 비밀번호 변경
    path("delete/", views.delete, name="delete"),  # 회원탈퇴
    path("<int:user_pk>/pre_delete/", views.pre_delete, name="pre_delete"),  # 회원탈퇴
    path("<int:pk>/update/", views.update, name="update"),  # 회원정보수정
    path(
        "password/reset/",
        views.UserPasswordResetView.as_view(
            template_name="accounts/password_reset.html",
            email_template_name="accounts/password_reset_email.html",
            success_url=reverse_lazy("accounts:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password/reset/done/",
        views.UserPasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password/reset/confirm/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy("accounts:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password/reset/confirm/complete/",
        views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("send_email/", views.send_email, name="send_email"),
    path("member/", views.member, name="member"),  # 프로그래스바
    path("login/kakao", views.kakao_request, name="kakao"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao_callback"),
]

articles/urls.py
from django.urls import path
from .views import baseviews, articleviews, commentviews

app_name = "articles"

urlpatterns = [
    path("", baseviews.index, name="index"),
    # 카테고리
    path('category/<int:pk>/', baseviews.category, name="category"),
    # 아티클
    path('create/', articleviews.article_create, name="create"),
    path('<int:article_pk>/update', articleviews.article_update, name="update"),
    path('<int:pk>/',articleviews.article_detail, name='detail'),
    path('<int:pk>/delete',articleviews.article_delete, name='delete'),
    # 신고
    path('<int:pk>/report',articleviews.article_report, name='article_report'),
    # 댓글 생성
    path("<int:pk>/comments/", commentviews.comment_create, name="comment_create"),
    # 댓글 삭제
    path(
        "<int:pk>/comment_delete/<int:comment_pk>",
        commentviews.comment_delete,
        name="comment_delete",
    ),
    # 게시글 좋아요
    path("<int:pk>/like/", articleviews.like, name="like"),
    # 댓글 좋아요
    path(
        "<int:article_pk>/like/<int:comment_pk>/",
        commentviews.comment_like,
        name="comment_like",
    ),
    # 게시물 북마크
    path("<int:pk>/bookmark/", articleviews.bookmark, name="bookmark"),
]

champions/urls.py
from django.urls import path
from . import views

app_name = "champions"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>/detail/", views.detail, name="detail"),
    path("goin/", views.goin, name="goin"),
    path("search/",views.search,name="search"),
]

summoners/urls.py
from django.urls import path, include
from . import views

app_name = "summoners"

urlpatterns = [
    path("test/", views.test, name="test"),
    path("", views.index, name="index"),
    path("result/", views.result, name="result"),
]

articles/views/baseviews.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib import messages
from ..forms import *
from ..models import *
from accounts.models import *
from django.http import HttpResponseForbidden
from django.db.models import Q, Avg, Count

# Create your views here.
def index(request):
    page = request.GET.get("page", "1")
    article = Article.objects.order_by("-created_at")
    kw = request.GET.get("kw", "")
    search_kind = request.GET.get("searchKind", "전체")
    sort = request.GET.get("sort", "")
    list1 = []
    for articles in article:
        if articles.top_fixed == True:
            list1.append(articles)
    grade = ''
    if request.user.is_authenticated:
        user = get_user_model().objects.get(pk=request.user.pk)
        article_set = user.article_set.all()
        comment_set = user.comment_set.all()
        a_count = article_set.count()
        c_count = comment_set.count()

        if c_count > 20 and a_count > 10:
            grade = '썩은물'
        elif c_count > 10 and a_count > 4:
            grade = '고인물'
        elif c_count > 2 and a_count > 2:
            grade = '탁한물'
        elif c_count > 2 or a_count > 0:
            grade = '맑은물'
        elif c_count <= 2 or a_count == 0:
            grade = '신선한물'

    # 추천순
    if sort == "1":
        article = (
            Article.objects.all()
            .annotate(like_cnt=Count("like_user"))
            .order_by("-like_cnt")
        )
    # 답글많은 순
    elif sort == "2":
        article = (
            Article.objects.all()
            .annotate(comments=Count("comment"))
            .order_by("-comments")
        )
    elif sort == "3":
        article = user.article_set.all()
    # 내가 와드 한 글
    elif sort == "4":
        article = user.bookmark_post.all()
    # 내가 좋아요 한 글
    elif sort == "5":
        article = user.like_post.all()
    if kw:
        if search_kind == "전체":
            article = article.filter(
                Q(title__icontains=kw)
                | Q(content__icontains=kw)  # 제목 검색
                | Q(user__username__icontains=kw)  # 내용 검색
            ).distinct()  # 질문 글쓴이 검색
        elif search_kind == "제목":
            article = article.filter(Q(title__icontains=kw)).distinct()  # 제목 검색
        elif search_kind == "내용":
            article = article.filter(Q(content__icontains=kw)).distinct()  # 내용 검색
        elif search_kind == "작성자":
            article = article.filter(
                Q(user__username__icontains=kw)  # 내용 검색
            ).distinct()
    if request.user.is_authenticated:
        user = get_user_model().objects.get(pk=request.user.pk)
    paginator = Paginator(article, 10)
    page_obj = paginator.get_page(page)
    categories = ["자유", "유머", "팬아트", "유저찾기", "유저뉴스", "팁과노하우", "기획", "사건사고"]
    
    # users = get_user_model().objects.get(pk=request.user.pk)
    # 회원등급 표시
    
    context = {
        "sort": sort,
        "article": page_obj,
        "page": page,
        "categories": categories,
        "kw": kw,
        "top_fixed": list1,
        "grade" : grade,
    }

    return render(request, "articles/index.html", context)

def category(request, pk):
    page = request.GET.get("page", "1")
    article = Article.objects.filter(category=pk).order_by("-created_at")
    kw = request.GET.get("kw", "")
    search_kind = request.GET.get("searchKind", "전체")
    sort = request.GET.get("sort", "")
    list1 = []
    for articles in article:
        if articles.top_fixed == True:
            list1.append(articles)
    grade = ''
    if request.user.is_authenticated:
        user = get_user_model().objects.get(pk=request.user.pk)
        article_set = user.article_set.all()
        comment_set = user.comment_set.all()
        a_count = article_set.count()
        c_count = comment_set.count()

        if c_count > 20 and a_count > 10:
            grade = '썩은물'
        elif c_count > 10 and a_count > 4:
            grade = '고인물'
        elif c_count > 2 and a_count > 2:
            grade = '탁한물'
        elif c_count > 2 or a_count > 0:
            grade = '맑은물'
        elif c_count <= 2 or a_count == 0:
            grade = '신선한물'
    # 추천순
    if sort == "1":
        article = (
            Article.objects.all()
            .annotate(like_cnt=Count("like_user"))
            .order_by("-like_cnt")
        )
    # 답글많은 순
    elif sort == "2":
        article = (
            Article.objects.all()
            .annotate(comments=Count("comment"))
            .order_by("-comments")
        )
    elif sort == "3":
        article = user.article_set.all()
    # 내가 와드 한 글
    elif sort == "4":
        article = user.bookmark_post.all()
    # 내가 좋아요 한 글
    elif sort == "5":
        article = user.like_post.all()
    if kw:
        if search_kind == "전체":
            article = article.filter(
                Q(title__icontains=kw)
                | Q(content__icontains=kw)  # 제목 검색
                | Q(user__username__icontains=kw)  # 내용 검색
            ).distinct()  # 질문 글쓴이 검색
        elif search_kind == "제목":
            article = article.filter(Q(title__icontains=kw)).distinct()  # 제목 검색
        elif search_kind == "내용":
            article = article.filter(Q(content__icontains=kw)).distinct()  # 내용 검색
        elif search_kind == "작성자":
            article = article.filter(
                Q(user__username__icontains=kw)  # 내용 검색
            ).distinct()
    paginator = Paginator(article, 10)
    page_obj = paginator.get_page(page)
    categories = ["자유", "유머", "팬아트", "유저찾기", "유저뉴스", "팁과노하우", "기획", "사건사고"]
    
    # users = get_user_model().objects.get(pk=request.user.pk)
    # 회원등급 표시
    
    category_name = categories[pk]
    context = {
        "sort": sort,
        "article": page_obj,
        "page": page,
        "categories": categories,
        "kw": kw,
        "grade" : grade,
        "top_fixed": list1,
        "category_name":category_name
    }
    return render(request, "articles/category.html", context)

templates/accountsBase.html
{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
<!doctype html>
<html lang="kr">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>RIP.GG {% block title %} {% endblock %}</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <!-- 부트스트랩 icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css%22%3E">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> -->
    <!-- 파비콘 -->
    <link rel="icon" type="image/png" href="/static/images/logo.png" sizes="16x16">
    <!-- 폰트어썸 -->
    <script src="https://kit.fontawesome.com/9dfbf66130.js" crossorigin="anonymous"></script>
    <!-- 폰트 CSS -->
    <link rel="stylesheet" href="{% static 'css/font.css' %}" type="text/css">
    <!-- accountsbase -->
    <link rel="stylesheet" href="{% static 'css/accountsBase.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/accountsDetail.css'%}" type="text/css">
    
</head>

    {% block style %}{% endblock style %}

<style>

</style>
</head>

    <header>
        <!-- /.fixed navigation -->
        <body data-spy="scroll" data-target="#scroll-spy">
            <!-- 어카운트 네브바 body 컨테이너가 없어야해서 따로 생성 -->
            <nav class="header_color d-flex">
                <header class="container d-flex flex-wrap justify-content-between align-content-center" style="">
                    <a href="{% url 'home' %}"
                        class="d-flex align-items-center mb-md-0 me-md-auto text-dark text-decoration-none">
                        <span class=""><img src="/static/images/흰로고.png" width="80" alt=""></span>
                    </a>
                    {% if request.user.is_authenticated %}
                    <div class="dropdown sm:display md:display">
                        <button class="dropbtn">
                            {{ request.user.username }}님
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <i class="px-1 fa-solid fa-chevron-down"></i>
                        </button>
                        <div class="dropdown-content" style="left: -10px;">
                            <a href="{% url 'accounts:detail' request.user.pk %}">내 정보</a>
                            <a href="{% url 'accounts:logout' %}">로그아웃</a>
                        </div>
                    </div>
                    <div class="dropdown md:display2 lg:display2">
                        <button class="dropbtn">
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <i class="fa-solid fa-user-check"></i>
                        </button>
                        <div class="dropdown-content dropdown-content2">
                            <a href="{% url 'accounts:detail' request.user.pk %}">내 정보</a>
                            <a href="{% url 'accounts:logout' %}">로그아웃</a>
                        </div>
                    </div>
                    {% else %}
                    <div class="sm:display2 md:display lg:display">
                        <div class="">
                          <div class="login">
                            <a class="" href="{% url 'accounts:login' %}">로그인</a>
                          </div>
                        </div>
                      </div>
                      <div class="sm:display md:display2 lg:display2">
                        <div class="smallinfo">
                            <a style="text-decoration: none;" href="{% url 'accounts:login' %}">로그인</a>
                        </div>
                      </div>
                    {% endif %}
                </header>
            </nav>
    </header>
    {% if user == request.user %}
    <nav class="mynav">
        <ul>
            <li><a href="{% url 'accounts:mypage' user.pk %}" >개인정보 관리</a></li>
            <li><a href="{% url 'accounts:password' user.pk %}" >비밀번호 변경</a></li>
            <li><a href="{% url 'accounts:pre_delete' user.pk %}" >탈퇴하기</a></li>
        </ul>
    </nav>
    {% endif %}
    <span class="target"></span>

    <main class="container">
        {% block content %}{% endblock content %}
    </main>
    <footer class="text-center mt-5 w-100 mb-2" style="bottom: 0">
        <!-- place footer here -->
        <span class="me-1" style="font-family: basic-ko; color: gray;">Final Project
            <span class="fw-bold">RIP.GG</span>
        </span>
        <a class="me-1" href="https://github.com/na-hyeong9" style="text-decoration: none; color: gray;">
            <img src="/static/images/nh.png" alt="" height="30px">
        </a>
        <a class="me-1" href="https://github.com/jelly12paw" style="text-decoration: none; color: gray;">
            <img src="/static/images/hj.png" alt="" height="30px">
        </a>
        <a class="me-1" href="https://github.com/kimbap918" style="text-decoration: none; color: gray;">
            <img src="/static/images/tl.png" alt="" height="30px">
        </a>
        <a class="me-1" href="https://github.com/wnsghd14" style="text-decoration: none; color: gray;">
            <img src="/static/images/jh.png" alt="" height="30px">
        </a>
        <a href="https://github.com/hady1024" style="text-decoration: none; color: gray;">
            <img src="/static/images/du.png" alt="" height="30px">
        </a>
    </footer>


    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
    <!-- Jquery needed -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script type="text/javascript"></script>
    <!-- AJAX CDN -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'js/accountBase.js' %}"></script>
    
    
</body>
{% block script %}{% endblock script %}
</html>

templates/base.html
{% load static %} {% load widget_tweaks %} {% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="kr">

<head>
  <link rel="shortcut icon" type="image/x-icon" href="#" />
  <title>RIP.gg {% block title %}{% endblock title %}</title>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" />
  <!-- 부트스트랩 icon -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css%22%3E" />
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> -->
  <!-- 파비콘 -->
  <link rel="icon" type="image/png" href="/static/images/logo.png" sizes="16x16" />
  <!-- 폰트어썸 -->
  <script src="https://kit.fontawesome.com/9dfbf66130.js" crossorigin="anonymous"></script>
  <!-- 폰트 CSS -->
  <link rel="stylesheet" href="{% static 'css/font.css' %}" type="text/css" />
  <!-- 로고 폰트 -->
  <link href="https://fonts.googleapis.com/css?family=Black+Han+Sans:400" rel="stylesheet" />
  <!-- base -->
  <link rel="stylesheet" href="{% static 'css/base.css'%}" type="text/css" />
  {% block style %}{% endblock style %}

  <style>
    a{
        text-decoration:none;
    }
  </style>
</head>

<body data-spy="scroll" data-target="#scroll-spy">
  <header>
    <nav class="navbar navbar-expand-lg" style="background-color: #5383e8; width: auto"
      aria-label="Eighth navbar example">
      <div class="container">
        <a href="{% url 'home' %}" class="d-flex align-items-center mb-md-0 me-md-auto text-dark text-decoration-none">
          <span class=""><img src="/static/images/흰로고.png" width="80" alt="" /></span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07"
          aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <div class="collapse navbar-collapse" id="navbarsExample07">
            <ul class="mynav navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a href="{% url 'champions:index' %}">챔피언</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'champions:goin' %}">고인</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'summoners:index' %}">소환사</a>
              </li>
              <li class="nav-item">
                <a href="{% url 'articles:index' %}">커뮤니티</a>
              </li>
            </ul>
            {% comment %} <div class="searchBox">
              <form role="search">
                <i
                  class="position-absolute fa-solid fa-magnifying-glass"
                  style="left: 1rem; bottom: 12px"></i>
                <input
                  class="form-control"
                  type="search"
                  placeholder="롤 전적.."
                  aria-label="Search"
                  style="padding-left: 2.5rem" />
              </form>
            </div> {% endcomment %}
            {% if request.user.is_authenticated %}
            <div class="sm:display2 md:display lg:display">
              <div class="dropdown">
                <button class="dropbtn">
                  <span style="font-size: 14px">{{ user.username }}님</span>
                  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                  <i class="px-1 fa-solid fa-chevron-down"></i>
                </button>
                <div class="dropdown-content">
                  <a href="{% url 'accounts:detail' user.pk %}">내 정보</a>
                  <a href="{% url 'accounts:logout' %}">로그아웃</a>
                </div>
              </div>
            </div>
            <div class="sm:display md:display2 lg:display2">
              <div class="smallinfo">
                <a href="{% url 'accounts:detail' user.pk %}">내 정보</a>
                <a href="{% url 'accounts:logout' %}">로그아웃</a>
              </div>
            </div>
          {% else %}
          <div class="sm:display2 md:display lg:display">
            <div class="">
              <div class="login">
                <a class="" href="{% url 'accounts:login' %}">로그인</a>
              </div>
            </div>
          </div>
          <div class="sm:display md:display2 lg:display2">
            <div class="smallinfo">
              <a style="text-decoration: none;" href="{% url 'accounts:login' %}">로그인</a>
            </div>
          </div>
          {% endif %}
        </div>
      </nav>
      <!-- /.fixed navigation -->
    </header>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    <!-- /.fixed navigation -->
  <main class="container">{% block content %}{% endblock content %}</main>
  <footer class="text-center mt-5 w-100 mb-2" style="bottom: 0">
    <!-- place footer here -->
    <span class="me-1" style="font-family: basic-ko; color: gray;">Final Project <span
        class="fw-bold">RIP.GG</span></span>
    <a class="me-1" href="https://github.com/na-hyeong9" style="text-decoration: none; color: gray;"><img
        src="/static/images/nh.png" alt="" height="30px"></a>
    <a class="me-1" href="https://github.com/jelly12paw" style="text-decoration: none; color: gray;"><img
        src="/static/images/hj.png" alt="" height="30px"></a>
    <a class="me-1" href="https://github.com/kimbap918" style="text-decoration: none; color: gray;"><img
        src="/static/images/tl.png" alt="" height="30px"></a>
    <a class="me-1" href="https://github.com/wnsghd14" style="text-decoration: none; color: gray;"><img
        src="/static/images/jh.png" alt="" height="30px"></a>
    <a href="https://github.com/hady1024" style="text-decoration: none; color: gray;"><img src="/static/images/du.png"
        alt="" height="30px"></a>
  </footer>

  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
    crossorigin="anonymous"></script>
  <!-- Jquery needed -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
  <script type="text/javascript"></script>
  <!-- AJAX CDN -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Function used to shrink nav bar removing paddings and adding black background -->
  <script>
    const target = document.querySelector(".target");
    const links = document.querySelectorAll(".mynav a");
    const colors = ["black", "#1ea1f7"];
    for (let i = 0; i < links.length; i++) {
      //links[i].addEventListener('click', (e) => e.preventDefault());
      links[i].addEventListener("mouseenter", mouseenterFunc);
      links[i].addEventListener("click", () => {
        let targetLink = this.getAttribute("href");
        location.href = targetLink;
      });
    }

    //parentNode 바로 위 부모요소
    function mouseenterFunc() {
      if (!this.parentNode.classList.contains("active")) {
        for (let i = 0; i < links.length; i++) {
          if (links[i].parentNode.classList.contains("active")) {
            links[i].parentNode.classList.remove("active");
          }
          links[i].style.opacity = "0.25";
        }

        //마우스가 올라갔을 때
        this.parentNode.classList.add("active");
        this.style.opacity = "1";

        const width = this.getBoundingClientRect().width;
        const height = this.getBoundingClientRect().height;
        const left = this.getBoundingClientRect().left + window.pageXOffset;
        const top = this.getBoundingClientRect().top + window.pageYOffset;
        // console.log(left);
        // console.log(top);
        const color = colors[Math.floor(Math.random() * links.length)];
        //target.style.width = width + 'px';
        target.style.width = width + "px";
        target.style.height = height + "px";
        target.style.left = left + "px";
        target.style.top = top + "px";
        target.style.borderColor = color;
      }
    }

    function resizeFunc() {
      const active = document.querySelector(".mynav li.active");

      if (active) {
        const left = this.getBoundingClientRect().left + window.pageXOffset;
        const top = this.getBoundingClientRect().top + window.pageYOffset;

        target.style.left = `$(left)px`;
        target.style.left = `$(top)px`;
      }
    }

    window.addEventListener("resize", resizeFunc);

    var url = window.location.pathname;
    $(".mynav")
      .find("a")
      .each(function () {
        $(this).toggleClass("active", $(this).attr("href") == url);
      });
  </script>

  {% block script %}{% endblock script %}
</body>

</html>